name: postgres-ip-whitelist

on: 
  workflow_dispatch:
    inputs:
      Firewall_Name:
        description: 'Firewall rule name'
        required: true
        type: string
        default: example-firewall-rule
      Start_IP_Address:
        description: 'Provide your IPv4 or IPv6 start address/range'
        required: true
        type: string
        default: 0.0.0.0
      End_IP_Address:
        description: 'Provide your IPv4 or IPv6 end address/range'
        required: true
        type: string
        default: 255.255.255.255

permissions:
  id-token: write
  contents: write

jobs:
  postgres_ip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Azure CLI
      uses: azure/setup-azure-cli@v3

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Whitelist IP in PostgreSQL
      run: |
        az postgres flexible-server firewall-rule create \
          --resource-group Mithun-RG \
          --name trumio-test \
          --rule-name "${{ github.event.inputs.Firewall_Name }}" \
          --start-ip-address "${{ github.event.inputs.Start_IP_Address }}" \
          --end-ip-address "${{ github.event.inputs.End_IP_Address }}"
